config/routes.rb
Rails.application.routes.draw do
  root to: 'categories#index'

  resources :transactions, except: :show
  resources :categories, only: [:show, :create, :index, :new]
  resources :accounts, except: :destroy
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :transactions
  include Balanceable

  def provider
    Provider.new(provider_slug)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :transactions
  include Balanceable
end

app/models/concerns/balanceable.rb
# frozen_string_literal: true

module Balanceable
  extend ActiveSupport::Concern

  def balance
    transactions.map(&:value).reduce(:+) || 0
  end
end

app/models/provider.rb
# frozen_string_literal: true

class Provider
  attr_reader :slug

  IMPORTERS_MAP = {
    sparda_bank: TransactionsImporter::SpardaBank
  }
  NAMES = {
    sparda_bank: 'Sparda Bank'
  }
  KNOWN_PROVIDERS = %i[sparda_bank]

  def self.all
    KNOWN_PROVIDERS.map {|provider_slug| new(provider_slug) }
  end

  def initialize(slug)
    if slug.nil?
      @slug = :default
    else
      @slug = slug.to_sym
    end
  end

  def transactions_importer
    IMPORTERS_MAP[slug] || TransactionsImporter::Default
  end

  def name
    NAMES[slug] || 'Default'
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :account
  belongs_to :category, optional: true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /accounts/1
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /accounts/1
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  def index
    @categories = Category.eager_load(:transactions)
    if filtered?
      @categories = @categories.where(
                    'transactions.booking_date >= ? AND transactions.booking_date <= ?',
                    min_date_filter, max_date_filter
                  )
    end
  end

  # GET /categories/1
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # POST /categories
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end

    def min_date_filter
      return DateTime.new(params[:year].to_i, params[:month].to_i).beginning_of_month if params[:month].present?
      DateTime.new(params[:year].to_i).beginning_of_year
    end

    def max_date_filter
      return DateTime.new(params[:year].to_i, params[:month].to_i).end_of_month if params[:month].present?
      DateTime.new(params[:year].to_i).end_of_year
    end

    def filtered?
      return true if params[:year].present?
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:edit, :update, :destroy]

  # GET /transactions
  def index
    @categories = Category.all
    @transactions = Transaction.all.includes(:account).where(category: nil)
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
    @accounts = Account.all
    @categories = Category.all
  end

  # POST /transactions
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to transactions_path, notice: 'Transaction was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /transactions/1
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transactions_path, notice: 'Transaction was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /transactions/1
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_path, notice: 'Transaction was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:booking_date, :payment_date, :purpose, :value, :currency, :account_id, :category_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  MONTH_SELECT_OPTIONS = [
    ['all', nil],
    ['January', '1'],
    ['February', '2'],
    ['March', '3'],
    ['April', '4'],
    ['May', '5'],
    ['June', '6'],
    ['July', '7'],
    ['August', '8'],
    ['September', '9'],
    ['October', '10'],
    ['November', '11'],
    ['December', '12']
  ].freeze
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :provider_name %>
    <%= form.select :provider_slug, Provider.all.collect {|p| [p.name, p.slug] }  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<p></p>

<h1>Editing Account</h1>

<%= render 'form', account: @account %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<%= link_to new_account_path, class: 'button' do %>
  <i class="em em-baby"></i> Create Account
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Balance</th>
      <th>Provider</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.name %></td>
        <td><%= number_to_currency(account.balance/100.0, unit: '', precision: 2) %></td>
        <td><%= account.provider.name %></td>
        <td>
          <%= link_to account do %>
            <i class="em em-card_file_box"></i>
          <% end %> | 
          <%= link_to edit_account_path(account) do %>
            <i class="em em-pencil2"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/accounts/new.html.erb
<p></p>

<h1>New Account</h1>

<%= render 'form', account: @account %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Transactions in <%= @account.name %></h1>

<%= link_to accounts_path, class: 'button' do %>
	<i class="em em-arrow_left"></i> Accounts
<% end %>

<table>
  <thead>
    <tr>
      <th>Booking date</th>
      <th>Payment date</th>
      <th>Purpose</th>
      <th>Value</th>
      <th>Account</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @account.transactions.order(payment_date: :desc).each do |transaction| %>
      <%= render 'transactions/list_item', transaction: transaction, inline_edit: false %>
    <% end %>
  </tbody>
</table>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<%= link_to new_category_path, class: 'button' do %>
  <i class="em em-baby"></i> Create Category
<% end %>

<%= form_tag categories_path, method: :get do %>
  <%= label(:year, :year) %>
  <%= select_tag :year, options_for_select([['all', nil], ['2018', 2018], ['2019', 2019]]) %>
  <%= label(:month, :month) %>
  <%= select_tag :month, options_for_select(CategoriesHelper::MONTH_SELECT_OPTIONS) %>
  <%= submit_tag 'Filter' %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th style="text-align:right;">Total</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td style="text-align:right;"><%= number_to_currency(category.balance/100.0, unit: '', precision: 2) %></td>
        <td>
          <%= link_to category do %>
            <i class="em em-card_file_box"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<p></p>

<h1>Create Category</h1>

<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Transactions in <%= @category.name %></h1>

<%= link_to categories_path, class: 'button' do %>
	<i class="em em-arrow_left"></i> Categories
<% end %>

<table>
  <thead>
    <tr>
      <th>Booking date</th>
      <th>Payment date</th>
      <th>Purpose</th>
      <th>Value</th>
      <th>Account</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @category.transactions.each do |transaction| %>
      <%= render 'transactions/list_item', transaction: transaction, inline_edit: false %>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">
    <link rel="stylesheet" href="//cdn.rawgit.com/necolas/normalize.css/master/normalize.css">
    <link rel="stylesheet" href="//cdn.rawgit.com/milligram/milligram/master/dist/milligram.min.css">
    <link href="https://afeld.github.io/emoji-css/emoji.css" rel="stylesheet">
  </head>

  <body>
    <div class="nav">
      <div class="container">
        <%= link_to root_path do %>
          <i class="em em-money_mouth_face"></i>
        <% end %>
        <%= link_to :categories, categories_path, class: 'button button-clear' %>
        <%= link_to :transactions, transactions_path, class: 'button button-clear' %>
        <%= link_to :accounts, accounts_path, class: 'button button-clear' %>
      </div>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, local: true) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :booking_date %>
    <%= form.date_select :booking_date %>
  </div>

  <div class="field">
    <%= form.label :payment_date %>
    <%= form.date_select :payment_date %>
  </div>

  <div class="field">
    <%= form.label :purpose %>
    <%= form.text_field :purpose %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.number_field :value %>
  </div>

  <div class="field">
    <%= form.label :currency %>
    <%= form.text_field :currency %>
  </div>

  <div class="field">
    <%= form.label :account %>
    <%= form.select :account_id, Account.all.collect {|a| [a.name, a.id] }, { include_blank: true }  %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.select :category_id, Category.all.collect {|c| [c.name, c.id] }, { include_blank: true }  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/_list_item.erb
<tr>
  <td><%= transaction.booking_date %></td>
  <td><%= transaction.payment_date %></td>
  <td><%= transaction.purpose %></td>
  <td style="text-align:right;"><%= number_to_currency(transaction.value/100.0, unit: '', precision: 2) %></td>
  <td><%= transaction.account.name if transaction.account %></td>
  <% if inline_edit %>
    <td>
      <%= form_with(model: transaction, local: true) do |form| %>
        <%= form.select :category_id, @categories.collect {|c| [c.name, c.id] }, { include_blank: true }  %>
        <%= form.submit 'Save' %>
      <% end %>
    </td>
  <% end %>
  <td>
  	<%= link_to edit_transaction_path(transaction) do %>
  		<i class="em em-pencil2"></i>
  	<% end %> | 	
  	<%= link_to transaction, method: :delete, data: { confirm: 'Are you sure you want to delete this transaction?' } do %>
  		<i class="em em-wastebasket"></i>
  	<% end %>
  </td>
</tr>

app/views/transactions/edit.html.erb
<p></p>

<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Uncategorized Transactions</h1>

<%= link_to new_transaction_path, class: 'button' do %>
  <i class="em em-baby"></i> Create Transaction
<% end %>

<table>
  <thead>
    <tr>
      <th>Booking date</th>
      <th>Payment date</th>
      <th>Purpose</th>
      <th>Value</th>
      <th>Account</th>
      <th>Category</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <%= render 'list_item', transaction: transaction, inline_edit: true %>
    <% end %>
  </tbody>
</table>

app/views/transactions/new.html.erb
<p></p>

<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>